### ISSUE TITLE
Canadian production host

### ISSUE THREAD

**Issue by leahtard** [maciejzgadzaj/moneris-api-ca#1]
It looks like the Canadian production host has changed since this library was written. I was using this library with the Drupal Commerce Moneris module and my transactions were failing to contact 'es.moneris.com'. After contacting Moneris support, they let em know that the host needs to be updated to 'www3.moneris.com' (on line 12).

**Comment by maciejzgadzaj** [comment]
Thanks Leah! The host has been changed in https://github.com/maciejzgadzaj/moneris-api-ca/commit/e9e98c71ad37bb7d708f214f491355d49891620f
